version: '3'
services:
  update:
    container_name: local-composer-update-request-test-app
    build:
      context: .
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
    volumes:
      - .:/github/workspace
    environment:
      - GITHUB_TOKEN
      - GITHUB_USER=takoba
      - GITHUB_REPOSITORY=takoba/composer-update-request-test-app
    command:
      bash -c "composer global require o0h/composer-update-request:dev-master && composer update"
