name: composer-update-request

on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP Action
        uses: shivammathur/setup-php@1.5.5
        with:
          php-version: 7.4
      - name: check composer's version
        run: composer -V

      - name: require composer-update-request package & update composer.lock
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: takoba
          GITHUB_REPOSITORY: takoba/composer-update-request-test-app
        run: |
          git config --global user.name "o0h/composer-update-request"
          git config --global user.email "plane25+takoba-composer-update-request-test-app@gmail.com"
          composer global config repositories.composer-update-request vcs https://github.com/takoba/composer-update-request
          composer global require o0h/composer-update-request:dev-master
          composer update
